version: '3'

services:

  web:
    build: ./dockSet
    depends_on:
      - db
    restart: always
    environment: 
      - APACHE_RUN_USER=#1000
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - 8080:80
    working_dir: ${APP_PATH_CONTAINER}       
  
  db:
    image: mariadb
    restart: always
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql
      - ./dockSet/backup.sql:/docker-entrypoint-initdb.d/dump.sql
    environment: 
      MYSQL_ROOT_PASSWORD: verylongpassword
      MYSQL_DATABASE: yourdatabase
      MYSQL_USER: eldar
      MYSQL_PASSWORD: changepass
      

  adminer:
      image: adminer
      restart: always
      ports: 
        - 6080:8080

  composer:
    image: composer:1.10.1 
    depends_on:
      - web
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}   
    working_dir: ${APP_PATH_CONTAINER} 
    command: composer install   